version: '3.7'
services:
  songassist-frontend:
    image: $NAME:$VERSION
    environment:
      - PORT=80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: 'true'
        traefik.http.routers.songassist-frontend.rule: Host(`songassist.ai`)
        traefik.http.routers.songassist-frontend.tls:
        traefik.http.routers.songassist-frontend.entrypoints: websecure
        traefik.http.services.songassist-frontend.loadbalancer.server.port: 80
    networks:
      - local

networks:
  local:
    external: true
    name: swarm-network
